{
    'name': 'Kg Project',
    'version': '17.0.1.0.0',
    'summary': 'Customizations for Project',
    'sequence': 100,
    'description': 'This module enhances Project functionalities.',
    'author': 'Klystron Global',
    'maintainer': 'Binu A R',
    'license': 'LGPL-3',
    'depends': ['base', 'project', 'account_accountant','sale_project'],
    'data': [
        'data/sequence_views.xml',
        'data/operation_type_views.xml',
        'security/ir.model.access.csv',
        'views/project_project_views.xml',
        'views/bom_category_views.xml',
        'views/bom_selection_views.xml',
        # 'views/material_requisition_views.xml',
        # 'views/purchase_requisitons_views.xml',
        # 'views/purchase_order_views.xml',
        'views/bom_master_views.xml',
        # 'wizards/invoice_from_project.xml',
        'wizards/import_bom_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
}
